### PR TITLE
isa removed

### LINKED ISSUE #20: Check all usage of `isa`
**Describe the solution you'd like**

Every time you can use `isa` you can also use a multi dispatch function (which lets the compiler do the hard work)
```julia
getval(x::IndexInt) = x.val
getval(x::Real) = x # bonus points here, we're still forcing the type rather than falling through to any, and look show short it is!
...
vals[node.label] = getval(obj)
```

### PR DESCRIPTION
**Pull request by iqml**
Thank you for your contribution. You're a :star: already!

Before submitting this PR, please have a look at the below checklist so that we know more about your PR.
Please also reference any relevant issues from the issues page if this PR is intended to address one of those.

## What does this PR do?

- [x] Describe what your pull request does:

- Some unnecessary uses of `isa` have been removed or replaced.
- resolves #20 

## Checklist

- [x] Your code builds clean without any errors or warnings
- [x] `julia --project -e 'using Pkg; Pkg.test()'` has been run locally and passes

### CODE REVIEW

**Review by yalwan-iqvia — APPROVED** [review]

**Comment by yalwan-iqvia** [comment]
Please merge upgraded CI first

**Comment by kd-iqvia** [comment]
is this partially addressing #20 ?

**Comment by yalwan-iqvia** [comment]
> is this partially addressing #20 ?

Indeed, seems like one spot was missed:

https://github.com/IQVIA-ML/TreeParzen.jl/blob/master/src/Resolve/nodes.jl#L17


```
walkable(x::Delayed.AbstractParam) = true
walkable(x) = false
```

should work just fine for this one

**Comment by iqml** [comment]
> > is this partially addressing #20 ?
> 
> Indeed, seems like one spot was missed:
> 
> https://github.com/IQVIA-ML/TreeParzen.jl/blob/master/src/Resolve/nodes.jl#L17
> 
> ```
> walkable(x::Delayed.AbstractParam) = true
> walkable(x) = false
> ```
> 
> should work just fine for this one

**Review by yalwan-iqvia — APPROVED** [review]

**Pull request merged**
