### PR TITLE
Add 1.6 to CI matrix

### PR DESCRIPTION
**Pull request by kd-iqvia**
Thank you for your contribution. You're a :star: already!

- updates CI to 1.6

### CODE REVIEW

**Review by yalwan-iqvia — APPROVED** [review]

**Comment by yalwan-iqvia** [comment]
@ablaom the CI failed with unsatisfiable requirements for 1.1 -- can you comment on what we might need to tweak in our Project.toml?

**Comment by ablaom** [comment]
I will have a look into this.

**Comment by ablaom** [comment]
@yalwan-iqvia  Suggest you close this in favour of https://github.com/IQVIA-ML/TreeParzen.jl/pull/62, which resolves the issue.

**Comment by yalwan-iqvia** [comment]
@ablaom has opened a new PR

**Pull request closed without merging**
