### PR TITLE
Add GH action CompatHelper

### PR DESCRIPTION
**Pull request by ablaom**
## What does this PR do?

- [x] Adds the CompatHelper GitHub action which automatically flags needed compatibility updates, creating a PR with the update ready for review.  

This PR does not effect code or tests.

To activate, an administrator must add  a Secret with the name "COMPATHELPER_PRIV" to this repo, together with a matching Deployment key (typically named "COMPATHELPER_PUB"). Instructions are [here](https://juliaregistries.github.io/CompatHelper.jl/dev/#Creating-SSH-Key).

These keys are set-up in this repo's "Settings" pane. 

@kd-iqvia

### CODE REVIEW

**Comment by yalwan-sage** [comment]
@ablaom the 1.6 tests failed with precompilation failures on MLJ packages. I noticed this locally also when I had an env with TreeParzen and some other deps, any idea as of the cause?

**Comment by kd-iqvia** [comment]
@yalwan-sage there's an opened issue: https://github.com/IQVIA-ML/TreeParzen.jl/issues/66 and there was indeed a problem with Distributions compatibility which was bumped to 0.25 and seemed to resolve the problem at least for Julia 1.6. However, I was also not able to add TPE to Julia 1.6.2. What worked for me though to make it work on Julia 1.6.0 was to clean up the precompiled cache first with this `rm -rf ~/.julia` which obviously is not a great solution but eventually it worked.

**Comment by ablaom** [comment]
@kd-iqvia This seems to be fine now, no?

**Comment by ablaom** [comment]
Just a reminder that for CompatHelper to work, RSA keys must be set up. See top comment above. 

You can check correct functioning by inspecting the "Actions" tab and then clicking on "CompatHelper" on the left side.

**Comment by kd-iqvia** [comment]
@ablaom yes I did that and got the first CompatHelper PR in 😄 This one we knew about but it's good to see the CompatHelper in action.

**Pull request merged**
